### ISSUE TITLE
Namespace declaration error in KirbyShopify.php

### ISSUE THREAD

**Issue by DodoVoelkel** [tristantbg/kirby-shopify#12]
Hey,
recently moved my hosting to Laravel Forge with php 8.0 and this error started appearing:
> Namespace declaration statement has to be the very first statement or after any declare call in the script

The debugger refers to this line:
https://github.com/tristantbg/kirby-shopify/blob/2064f61bd729e9fe3f364320e9528cb1fbe6a751/src/KirbyShopify.php#L6

**Comment by timstaana** [comment]
Hey @DodoVoelkel I've made pull request for fixing the issue here #13
