### ISSUE TITLE
3.8 compatibility

### ISSUE THREAD

**Issue by afbora** [tristantbg/kirby-shopify#14]
> Namespace declaration statement has to be the very first statement or after any declare call in the script

**Comment by tristantbg** [comment]
This has been changed a long time ago but forgot to push a new tag for Packagist.
Should be good to pull from composer now.

**Comment by afbora** [comment]
Yes working now. But few minor issues left for 3.8 update check

> Missing composer.json version
> Plugin name doesn't match with getkirby.com

- getkirby uri: `tristanbg/shopify`
  https://getkirby.com/plugins/tristanbg/shopify
- plugin register: `tristanb/kirby-shopify`
  > Kirby::plugin('tristanb/kirby-shopify', []);

**Comment by tristantbg** [comment]
What do I have to change ?

**Comment by afbora** [comment]
1. Add `version` info to plugin composer.json
2. In order for the update to be checked correctly, the plugin registration name and the uri in getkirby.com must be the same. Either we have to update the uri on getkirby.com or the plugin registration name.

Since changing the plugin registration name of the plugin will be a breaking change, I suggest just changing the uri on getkirby.com as follows (same with plugin register name). What do you think?

> https://getkirby.com/plugins/tristanb/kirby-shopify

**Comment by tristantbg** [comment]
Just added the version !

_Since changing the plugin registration name of the plugin will be a breaking change, I suggest just changing the uri on getkirby.com as follows (same with plugin register name). What do you think?
https://getkirby.com/plugins/tristanb/kirby-shopify_

Yes that would be the best because I use this naming in the plugin... many thanks !

**Comment by afbora** [comment]
✅ Done https://github.com/getkirby/getkirby.com/commit/d6ac87229b398bdc76c87498437f321d7211fe43
