### ISSUE TITLE
 The section "products" could not be loaded: [API] Invalid API key or access token (unrecognized login or wrong password) 

### ISSUE THREAD

**Issue by paubou** [tristantbg/kirby-shopify#15]
I've set all the required informations in my `.env` file but somehow I cannot seem to access my panel/product page.
SHOP_URL= is set to myshop.myshopify.com and working great
API_KEY=
API_PASSWORD=
are set to this :
<img width="592" alt="Capture d’écran 2022-12-05 à 16 32 43" src="https://user-images.githubusercontent.com/7825891/205677163-76ac90cd-7c67-4364-8d94-5cca89b0f5da.png">

SHOPIFY_APP_SECRET=
is set to the yellow very long character chain:
<img width="808" alt="Capture d’écran 2022-12-05 à 16 35 14" src="https://user-images.githubusercontent.com/7825891/205677789-00060c98-40de-428d-abf0-5d17c48f8163.png">

ACCESS_TOKEN= is set to
<img width="582" alt="Capture d’écran 2022-12-05 à 16 34 08" src="https://user-images.githubusercontent.com/7825891/205677360-f10d6eb6-02e9-4525-83a0-a5cda051dbc9.png">

But as soon as I go to my panel, to the products page, the error : ` The section "products" could not be loaded: [API] Invalid API key or access token (unrecognized login or wrong password) ` is thrown.

I can't seem to manage to understand where this comes from.
Also, the `Admin API access token` is never used in that case, maybe I'm misunderstanding things.

**Comment by tristantbg** [comment]
Shopify has changed a few things and I need to update the readme and plugin.

You need to use the **Admin API access token** for the API_PASSWORD !
<img width="554" alt="Capture d’écran 2022-12-06 à 22 23 44" src="https://user-images.githubusercontent.com/4832038/206032381-e230599d-1981-4ac4-bd28-33446060876c.png">

**Comment by paubou** [comment]
Thanks @tristantbg ! However, the change seems to have greyed out the option to edit the item.
Probably because of the webhooks? As the previous screenshot suggest, my webhooks are great though.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/7825891/206196146-1cf2b280-0075-46ea-9db4-ab26c308b9b6.png">

**Comment by tristantbg** [comment]
That's normal, the title shown here is the one written on Shopify, if you want to update it you need to update it on Shopify.
That's what the plugin is meant to do 😅

**Comment by paubou** [comment]
thanks I guessed that after seing some screehshots on the forums...
The first issue made me bogusly vigilant haha. 😖
