### ISSUE TITLE
Enable "Collection create", "Collection update", "Collection delete" in shopify not possible

### ISSUE THREAD

**Issue by toh82** [tristantbg/kirby-shopify#16]
I wanted to get this started but on the shopify app config  "Collection create", "Collection update", "Collection delete" are not availabe to choose from within "Configuration -> Admin-API-Integration". 

What can I do?

**Comment by toh82** [comment]
Also in the Shopify backend there is no possibility to add webhook urls or something.

**Comment by tristantbg** [comment]
Please read the documentation :
https://etudes-studio.myshopify.com/admin/settings/notifications

**Comment by tristantbg** [comment]
Please read the documentation.
Webhooks are here :
https://xxx.myshopify.com/admin/settings/notifications

**Comment by toh82** [comment]
@tristantbg thanks. somehow I did now recognize this link with the configuration. okay wild. I'm sorry
