### ISSUE TITLE
Manual collections don't appear in Kirby

### ISSUE THREAD

**Issue by baalej** [tristantbg/kirby-shopify#19]
Hi,

First, thank you so much for your work on the plugin.

I wanted to share an issue I am experiencing with Collections.

I created a Collection A (manual) on Shopify and added some products to it manually.
Then I created a second collection Collection B (automatic) with some condition for example, when the product tag contains 'Collection B'.

On my site, within the collections page, only the second collection (B) ,with the condition, appears, while the first one, it doesn't appear, even though it also contains some products.

Is there a way to display the manual collections as well?

**Comment by tristantbg** [comment]
Unfortunately that's a known issue... the whole plugin needs to be rewritten using GraphQL..
You have to create collections inside Kirby instead.

**Comment by baalej** [comment]
Thank you for the quick reply!
I see, but those collections created in Kirby only exist there, right?

**Comment by tristantbg** [comment]
Yes... you need to create a **pages** field

**Comment by baalej** [comment]
Got it, thank you
