### ISSUE TITLE
New products are not listed

### ISSUE THREAD

**Issue by freddie-freeloader** [tristantbg/kirby-shopify#2]
Hi there!

Thank you so much for your library! :blush: 

Sorry, if this issue is too unspecific, but maybe, this issue does ring a bell or might be here for others who also encounter this situation:

---

For some reason, newly created products are not shown. *But* if I duplicate a product in Shopify, the newly created duplicate will be listed.

Regularly created products are listed, when I query the REST-API manually (with the same credentials).

---

Any ideas what might cause this behavior?

And please excuse me, if this issue is too unspecific.

**Comment by tristantbg** [comment]
Hi @freddie-freeloader 

Thank you for your message.

Are you sure you have setup your Webhooks on Shopify properly ? Also, are you on localhost or a public server ?

Best,
T
