### ISSUE TITLE
Changing status to draft breaks entire products page

### ISSUE THREAD

**Issue by sammularczyk** [tristantbg/kirby-shopify#6]
When you change the product page to Draft, the entire thing breaks - you can't change it back to unlisted or public either.

The error I get is
`Call to a member function root() on null`

Only way to fix it is to manually SSH in and move it out from Drafts.

**Comment by tristantbg** [comment]
Actually I don't see the purpose of putting this page in Draft instead of Unlisted...
I would rather block the possibility to change the status instead.
