### ISSUE TITLE
Filter by Shopify's product status

### ISSUE THREAD

**Issue by ian-cox** [tristantbg/kirby-shopify#8]
Is there a way to filter by Shopify's product status?
https://shopify.dev/docs/admin-api/graphql/reference/products-and-collections/productstatus

If not is there any way hide/show a product without deleting it from Shopify?
Setting a product to Draft or Archived seems to have no affect on the information coming into the panel.

Currently the only way for me to remove a product from being displayed is to completely delete it from Shopify.

**Comment by tristantbg** [comment]
Thank you for your feedback.
Since this is quite new to Shopify, I didn't put any filtering with status.
This is now implemented in the last version.
Let me know if it works.
Best
